### ISSUE TITLE
"OpenMC aborted unexpectedly" when trying to plot_geometry() in Jupyter Notebook

### ISSUE THREAD

**Issue by shahbazi784** [openmc-dev/openmc#2400]
Conditions: Macbook Pro, miniconda -> make new env (python3.11) -> install mamba -> install openmc -> using Jupyter Notebook:

I am following the Pin-Cell Jupyter notebook exactly and everything seems to work perfectly except for these two plotting commands produce the same error of "OpenMC aborted unexpectedly":

`universe.plot(width=(2.0, 2.0), origin=(0.0, 0.0, 0.1))`

or 

`openmc.plot_geometry()`

results in the following error:

`                                %%%%%%%%%%%%%%%
                           %%%%%%%%%%%%%%%%%%%%%%%%
                        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                                    %%%%%%%%%%%%%%%%%%%%%%%%
                                     %%%%%%%%%%%%%%%%%%%%%%%%
                 ###############      %%%%%%%%%%%%%%%%%%%%%%%%
                ##################     %%%%%%%%%%%%%%%%%%%%%%%
                ###################     %%%%%%%%%%%%%%%%%%%%%%%
                ####################     %%%%%%%%%%%%%%%%%%%%%%
                #####################     %%%%%%%%%%%%%%%%%%%%%
                ######################     %%%%%%%%%%%%%%%%%%%%
                #######################     %%%%%%%%%%%%%%%%%%
                 #######################     %%%%%%%%%%%%%%%%%
                 ######################     %%%%%%%%%%%%%%%%%
                  ####################     %%%%%%%%%%%%%%%%%
                    #################     %%%%%%%%%%%%%%%%%
                     ###############     %%%%%%%%%%%%%%%%
                       ############     %%%%%%%%%%%%%%%
                          ########     %%%%%%%%%%%%%%
                                      %%%%%%%%%%%

                 | The OpenMC Monte Carlo Code
       Copyright | 2011-2022 MIT, UChicago Argonne LLC, and contributors
         License | https://docs.openmc.org/en/latest/license.html
         Version | 0.13.2
       Date/Time | 2023-02-24 12:43:33
   MPI Processes | 1
  OpenMP Threads | 8

 Reading settings XML file...
 Reading cross sections XML file...
 Reading materials XML file...
 Reading geometry XML file...
 Reading tallies XML file...
 Preparing distributed cell instances...
 Reading plot XML file...

 =======================>     PLOTTING SUMMARY     <========================

Plot ID: 1
Plot file: pinplot.png
Universe depth: -1
Plot Type: Slice
Origin: 0 0 0
Width: 1.26 1.26
Coloring: Materials
Basis: XY
Pixels: 200 200

 Processing plot 1: pinplot.png...
libpng warning: Application built with libpng-1.4.12 but running with 1.6.39
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[20], line 1
----> 1 openmc.plot_geometry()

File ~/miniconda3/envs/openmc/lib/python3.11/site-packages/openmc/executor.py:139, in plot_geometry(output, openmc_exec, cwd)
    121 def plot_geometry(output=True, openmc_exec='openmc', cwd='.'):
    122     """Run OpenMC in plotting mode
    123 
    124     Parameters
   (...)
    137 
    138     """
--> 139     _run([openmc_exec, '-p'], output, cwd)

File ~/miniconda3/envs/openmc/lib/python3.11/site-packages/openmc/executor.py:118, in _run(args, output, cwd)
    115     error_msg = 'OpenMC aborted unexpectedly.'
    116 error_msg = ' '.join(error_msg.split())
--> 118 raise RuntimeError(error_msg)

RuntimeError: OpenMC aborted unexpectedly.
`

**Comment by paulromano** [comment]
@shahbazi784 We just updated the package on conda-forge in an attempt to fix the issue here with libpng. Can you try updating your conda openmc package and see if that fixes the issue?

**Comment by shahbazi784** [comment]
@paulromano I did both "mamba update -c conda-forge openmc" and then I did "conda update openmc", and I still get the same error.
